[system]
AUDIO_TEMP_DIR="/dev/shm"
DEPLOYMENT_NAME="ASRService"
VAD_DEPLOYMENT_NAME="VADService"
RAY_HOST="0.0.0.0"
RAY_PORT=8000

[asr]
ASR_NUM_GPUS=0.2
ASR_NUM_REPLICAS=1
ASR_MAX_ONGOING_REQUESTS=8
ASR_MAX_BATCH_SIZE=8
ASR_BATCH_WAIT_TIMEOUT_S=0.1

[vad]
VAD_MODEL_NAME="pyannote/segmentation-3.0"
VAD_DEVICE="auto"
VAD_NUM_GPUS=0.1
VAD_NUM_REPLICAS=4
VAD_MAX_ONGOING_REQUESTS=8

[ingress]
INGRESS_NUM_GPUS=0
INGRESS_NUM_REPLICAS=1
INGRESS_MAX_ONGOING_REQUESTS=16

