[system]
AUDIO_TEMP_DIR="/dev/shm"
VAD_DEPLOYMENT_NAME="VADService"
RAY_HOST="0.0.0.0"
RAY_PORT=8000

[serving]
NUM_GPUS=1
NUM_REPLICAS=1
MAX_ONGOING_REQUESTS=4

[vad]
VAD_MODEL_NAME="pyannote/segmentation-3.0"
VAD_DEVICE="auto"

